# Generated by Django 3.2.12 on 2022-04-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=75)),
                ('zip_code', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
